

const CriteriaTypes = 
[
    'CRITERIA_TYPE_KILL_CREATURE                 '        ,
    'CRITERIA_TYPE_WIN_BG                        '        ,
    '// 2 - unused (Legion - 23420)'                      ,
    'CRITERIA_TYPE_COMPLETE_ARCHAEOLOGY_PROJECTS '        , // struct { uint32 itemCount; }
    'CRITERIA_TYPE_SURVEY_GAMEOBJECT             '        ,
    'CRITERIA_TYPE_REACH_LEVEL                   '        ,
    'CRITERIA_TYPE_CLEAR_DIGSITE                 '        ,
    'CRITERIA_TYPE_REACH_SKILL_LEVEL             '        ,
    'CRITERIA_TYPE_COMPLETE_ACHIEVEMENT          '        ,
    'CRITERIA_TYPE_COMPLETE_QUEST_COUNT          '        ,
    'CRITERIA_TYPE_COMPLETE_DAILY_QUEST_DAILY    '        , // you have to complete a daily quest x times in a row
    'CRITERIA_TYPE_COMPLETE_QUESTS_IN_ZONE       '        ,
    'CRITERIA_TYPE_CURRENCY                      '        ,
    'CRITERIA_TYPE_DAMAGE_DONE                   '        ,
    'CRITERIA_TYPE_COMPLETE_DAILY_QUEST          '        ,
    'CRITERIA_TYPE_COMPLETE_BATTLEGROUND         '        ,
    'CRITERIA_TYPE_DEATH_AT_MAP                  '        ,
    'CRITERIA_TYPE_DEATH                         '        ,
    'CRITERIA_TYPE_DEATH_IN_DUNGEON              '        ,
    'CRITERIA_TYPE_COMPLETE_RAID                 '        ,
    'CRITERIA_TYPE_KILLED_BY_CREATURE            '        ,
    'CRITERIA_TYPE_MANUAL_COMPLETE_CRITERIA      '        ,
    'CRITERIA_TYPE_COMPLETE_CHALLENGE_MODE_GUILD '        ,
    'CRITERIA_TYPE_KILLED_BY_PLAYER              '        ,
    'CRITERIA_TYPE_FALL_WITHOUT_DYING            '        ,
    '// 25 - unused (Legion - 23420)'            ,
    'CRITERIA_TYPE_DEATHS_FROM                       '    ,
    'CRITERIA_TYPE_COMPLETE_QUEST                    '    ,
    'CRITERIA_TYPE_BE_SPELL_TARGET                   '    ,
    'CRITERIA_TYPE_CAST_SPELL                        '    ,
    'CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE              '    ,
    'CRITERIA_TYPE_HONORABLE_KILL_AT_AREA            '    ,
    'CRITERIA_TYPE_WIN_ARENA                         '    ,
    'CRITERIA_TYPE_PLAY_ARENA                        '    ,
    'CRITERIA_TYPE_LEARN_SPELL                       '    ,
    'CRITERIA_TYPE_HONORABLE_KILL                    '    ,
    'CRITERIA_TYPE_OWN_ITEM                          '    ,
    'CRITERIA_TYPE_WIN_RATED_ARENA                   '    ,
    'CRITERIA_TYPE_HIGHEST_TEAM_RATING               '    ,
    'CRITERIA_TYPE_HIGHEST_PERSONAL_RATING           '    ,
    'CRITERIA_TYPE_LEARN_SKILL_LEVEL                 '    ,
    'CRITERIA_TYPE_USE_ITEM                          '    ,
    'CRITERIA_TYPE_LOOT_ITEM                         '    ,
    'CRITERIA_TYPE_EXPLORE_AREA                      '    ,
    'CRITERIA_TYPE_OWN_RANK                          '    ,
    'CRITERIA_TYPE_BUY_BANK_SLOT                     '    ,
    'CRITERIA_TYPE_GAIN_REPUTATION                   '    ,
    'CRITERIA_TYPE_GAIN_EXALTED_REPUTATION           '    ,
    'CRITERIA_TYPE_VISIT_BARBER_SHOP                 '    ,
    'CRITERIA_TYPE_EQUIP_EPIC_ITEM                   '    ,
    'CRITERIA_TYPE_ROLL_NEED_ON_LOOT                 '    , /// @todo itemlevel is mentioned in text but not present in dbc
    'CRITERIA_TYPE_ROLL_GREED_ON_LOOT                '    ,
    'CRITERIA_TYPE_HK_CLASS                          '    ,
    'CRITERIA_TYPE_HK_RACE                           '    ,
    'CRITERIA_TYPE_DO_EMOTE                          '    ,
    'CRITERIA_TYPE_HEALING_DONE                      '    ,
    'CRITERIA_TYPE_GET_KILLING_BLOWS                 '    , /// @todo in some cases map not present, and in some cases need do without die
    'CRITERIA_TYPE_EQUIP_ITEM                        '    ,
    '// 58 - unused (Legion - 23420)' ,
    'CRITERIA_TYPE_MONEY_FROM_VENDORS                '    ,
    'CRITERIA_TYPE_GOLD_SPENT_FOR_TALENTS            '    ,
    'CRITERIA_TYPE_NUMBER_OF_TALENT_RESETS           '    ,
    'CRITERIA_TYPE_MONEY_FROM_QUEST_REWARD           '    ,
    'CRITERIA_TYPE_GOLD_SPENT_FOR_TRAVELLING         '    ,
    'CRITERIA_TYPE_DEFEAT_CREATURE_GROUP             '    ,
    'CRITERIA_TYPE_GOLD_SPENT_AT_BARBER               '   ,
    'CRITERIA_TYPE_GOLD_SPENT_FOR_MAIL                '   ,
    'CRITERIA_TYPE_LOOT_MONEY                         '   ,
    'CRITERIA_TYPE_USE_GAMEOBJECT                     '   ,
    'CRITERIA_TYPE_BE_SPELL_TARGET2                   '   ,
    'CRITERIA_TYPE_SPECIAL_PVP_KILL                   '   ,
    'CRITERIA_TYPE_COMPLETE_CHALLENGE_MODE            '   ,
    'CRITERIA_TYPE_FISH_IN_GAMEOBJECT                 '   ,
    'CRITERIA_TYPE_SEND_EVENT                         '   ,
    'CRITERIA_TYPE_ON_LOGIN                           '   ,
    'CRITERIA_TYPE_LEARN_SKILLLINE_SPELLS             '   ,
    'CRITERIA_TYPE_WIN_DUEL                           '   ,
    'CRITERIA_TYPE_LOSE_DUEL                          '   ,
    'CRITERIA_TYPE_KILL_CREATURE_TYPE                 '   ,
    'CRITERIA_TYPE_COOK_RECIPES_GUILD                 '   ,
    'CRITERIA_TYPE_GOLD_EARNED_BY_AUCTIONS            '   ,
    'CRITERIA_TYPE_EARN_PET_BATTLE_ACHIEVEMENT_POINTS '   ,
    'CRITERIA_TYPE_CREATE_AUCTION                     '   ,
    'CRITERIA_TYPE_HIGHEST_AUCTION_BID                '   ,
    'CRITERIA_TYPE_WON_AUCTIONS                       '   ,
    'CRITERIA_TYPE_HIGHEST_AUCTION_SOLD               '   ,
    'CRITERIA_TYPE_HIGHEST_GOLD_VALUE_OWNED           '   ,
    'CRITERIA_TYPE_GAIN_REVERED_REPUTATION            '   ,
    'CRITERIA_TYPE_GAIN_HONORED_REPUTATION            '   ,
    'CRITERIA_TYPE_KNOWN_FACTIONS                     '   ,
    'CRITERIA_TYPE_LOOT_EPIC_ITEM                     '   ,
    'CRITERIA_TYPE_RECEIVE_EPIC_ITEM                  '   ,
    'CRITERIA_TYPE_SEND_EVENT_SCENARIO                '   ,
    'CRITERIA_TYPE_ROLL_NEED                          '   ,
    'CRITERIA_TYPE_ROLL_GREED                         '   ,
    'CRITERIA_TYPE_RELEASE_SPIRIT                     '   ,
    'CRITERIA_TYPE_OWN_PET                            '   ,
    'CRITERIA_TYPE_GARRISON_COMPLETE_DUNGEON_ENCOUNTER'   ,
    '// 98 - unused (Legion - 23420)',
    '// 99 - unused (Legion - 23420)',
    '// 100 - unused (Legion - 23420)',
    'CRITERIA_TYPE_HIGHEST_HIT_DEALT                  '   ,
    'CRITERIA_TYPE_HIGHEST_HIT_RECEIVED               '   ,
    'CRITERIA_TYPE_TOTAL_DAMAGE_RECEIVED              '   ,
    'CRITERIA_TYPE_HIGHEST_HEAL_CAST                  '   ,
    'CRITERIA_TYPE_TOTAL_HEALING_RECEIVED             '   ,
    'CRITERIA_TYPE_HIGHEST_HEALING_RECEIVED           '   ,
    'CRITERIA_TYPE_QUEST_ABANDONED                      ' ,
    'CRITERIA_TYPE_FLIGHT_PATHS_TAKEN                   ' ,
    'CRITERIA_TYPE_LOOT_TYPE                            ' ,
    'CRITERIA_TYPE_CAST_SPELL2                          ' , /// @todo target entry is missing
    '// 111 - unused (Legion - 23420)                   ' ,
    'CRITERIA_TYPE_LEARN_SKILL_LINE                     ' ,
    'CRITERIA_TYPE_EARN_HONORABLE_KILL                  ' ,
    'CRITERIA_TYPE_ACCEPTED_SUMMONINGS                  ' ,
    'CRITERIA_TYPE_EARN_ACHIEVEMENT_POINTS              ' ,
    '// 116 - unused (Legion - 23420)                   '         ,
    '// 117 - unused (Legion - 23420)                   ' ,
    'CRITERIA_TYPE_COMPLETE_LFG_DUNGEON                 ' ,
    'CRITERIA_TYPE_USE_LFD_TO_GROUP_WITH_PLAYERS        ' ,
    'CRITERIA_TYPE_LFG_VOTE_KICKS_INITIATED_BY_PLAYER   ' ,
    'CRITERIA_TYPE_LFG_VOTE_KICKS_NOT_INIT_BY_PLAYER    ' ,
    'CRITERIA_TYPE_BE_KICKED_FROM_LFG                   ' ,
    'CRITERIA_TYPE_LFG_LEAVES                           ' ,
    'CRITERIA_TYPE_SPENT_GOLD_GUILD_REPAIRS             ' ,
    'CRITERIA_TYPE_REACH_GUILD_LEVEL                    ' ,
    'CRITERIA_TYPE_CRAFT_ITEMS_GUILD                    ' ,
    'CRITERIA_TYPE_CATCH_FROM_POOL                      ' ,
    'CRITERIA_TYPE_BUY_GUILD_BANK_SLOTS                 ' ,
    'CRITERIA_TYPE_EARN_GUILD_ACHIEVEMENT_POINTS        ' ,
    'CRITERIA_TYPE_WIN_RATED_BATTLEGROUND               ' ,
    '// 131 - unused (Legion - 23420)                   ' ,
    'CRITERIA_TYPE_REACH_BG_RATING                      ' ,
    'CRITERIA_TYPE_BUY_GUILD_TABARD                     ' ,
    'CRITERIA_TYPE_COMPLETE_QUESTS_GUILD                ' ,
    'CRITERIA_TYPE_HONORABLE_KILLS_GUILD                ' ,
    'CRITERIA_TYPE_KILL_CREATURE_TYPE_GUILD             ' ,
    'CRITERIA_TYPE_COUNT_OF_LFG_QUEUE_BOOSTS_BY_TANK    ' ,
    'CRITERIA_TYPE_COMPLETE_GUILD_CHALLENGE_TYPE        ' , //struct { Flag flag; uint32 count; } 1: Guild Dungeon, 2:Guild Challenge, 3:Guild battlefield
    'CRITERIA_TYPE_COMPLETE_GUILD_CHALLENGE             ' , //struct { uint32 count; } Guild Challenge
    '// 140 - 1 criteria (16883), unused (Legion - 23420',
    '// 141 - 1 criteria (16884), unused (Legion - 23420',
    '// 142 - 1 criteria (16881), unused (Legion - 23420',
    '// 143 - 1 criteria (16882), unused (Legion - 23420',
    '// 144 - 1 criteria (17386), unused (Legion - 23420',
    'CRITERIA_TYPE_LFR_DUNGEONS_COMPLETED               ' ,
    'CRITERIA_TYPE_LFR_LEAVES                           ' ,
    'CRITERIA_TYPE_LFR_VOTE_KICKS_INITIATED_BY_PLAYER   ' ,
    'CRITERIA_TYPE_LFR_VOTE_KICKS_NOT_INIT_BY_PLAYER    ' ,
    'CRITERIA_TYPE_BE_KICKED_FROM_LFR                   ' ,
    'CRITERIA_TYPE_COUNT_OF_LFR_QUEUE_BOOSTS_BY_TANK    ' ,
    'CRITERIA_TYPE_COMPLETE_SCENARIO_COUNT              ' ,
    'CRITERIA_TYPE_COMPLETE_SCENARIO                    ' ,
    'CRITERIA_TYPE_REACH_AREATRIGGER_WITH_ACTIONSET     ' ,
    '// 154 - unused (Legion - 23420)',
    'CRITERIA_TYPE_OWN_BATTLE_PET                       ' ,
    'CRITERIA_TYPE_OWN_BATTLE_PET_COUNT                 ' ,
    'CRITERIA_TYPE_CAPTURE_BATTLE_PET                   ' ,
    'CRITERIA_TYPE_WIN_PET_BATTLE                       ' ,
    '// 159 - 2 criterias (22312,22314), unused (Legion ',
    'CRITERIA_TYPE_LEVEL_BATTLE_PET                     ' ,
    'CRITERIA_TYPE_CAPTURE_BATTLE_PET_CREDIT            ' , // triggers a quest credit
    'CRITERIA_TYPE_LEVEL_BATTLE_PET_CREDIT              ' , // triggers a quest credit
    'CRITERIA_TYPE_ENTER_AREA                           ' , // triggers a quest credit
    'CRITERIA_TYPE_LEAVE_AREA                           ' , // triggers a quest credit
    'CRITERIA_TYPE_COMPLETE_DUNGEON_ENCOUNTER           ' ,
    '// 166 - unused (Legion - 23420)',
    'CRITERIA_TYPE_PLACE_GARRISON_BUILDING              ' ,
    'CRITERIA_TYPE_UPGRADE_GARRISON_BUILDING            ' ,
    'CRITERIA_TYPE_CONSTRUCT_GARRISON_BUILDING          ' ,
    'CRITERIA_TYPE_UPGRADE_GARRISON                     ' ,
    'CRITERIA_TYPE_START_GARRISON_MISSION               ' ,
    'CRITERIA_TYPE_START_ORDER_HALL_MISSION             ' ,
    'CRITERIA_TYPE_COMPLETE_GARRISON_MISSION_COUNT      ' ,
    'CRITERIA_TYPE_COMPLETE_GARRISON_MISSION            ' ,
    'CRITERIA_TYPE_RECRUIT_GARRISON_FOLLOWER_COUNT      ' ,
    'CRITERIA_TYPE_RECRUIT_GARRISON_FOLLOWER            ' ,
    '// 177 - 0 criterias (Legion - 23420)',
    'CRITERIA_TYPE_LEARN_GARRISON_BLUEPRINT_COUNT       ' ,
    '// 179 - 0 criterias (Legion - 23420)',
    '// 180 - 0 criterias (Legion - 23420)',
    '// 181 - 0 criterias (Legion - 23420)',
    'CRITERIA_TYPE_COMPLETE_GARRISON_SHIPMENT           ' ,
    'CRITERIA_TYPE_RAISE_GARRISON_FOLLOWER_ITEM_LEVEL   ' ,
    'CRITERIA_TYPE_RAISE_GARRISON_FOLLOWER_LEVEL        ' ,
    'CRITERIA_TYPE_OWN_TOY                              ' ,
    'CRITERIA_TYPE_OWN_TOY_COUNT                        ' ,
    'CRITERIA_TYPE_RECRUIT_GARRISON_FOLLOWER_WITH_QUALITY',
    '// 188 - 0 criterias (Legion - 23420)',
    'CRITERIA_TYPE_OWN_HEIRLOOMS                        ' ,
    'CRITERIA_TYPE_ARTIFACT_POWER_EARNED                ' ,
    'CRITERIA_TYPE_ARTIFACT_TRAITS_UNLOCKED             ' ,
    'CRITERIA_TYPE_HONOR_LEVEL_REACHED                  ' ,
    'CRITERIA_TYPE_PRESTIGE_REACHED                     ' ,
    '// 196 - CRITERIA_TYPE_REACH_LEVEL_2 or something',
    '// 197 - Order Hall Advancement related',
    'CRITERIA_TYPE_ORDER_HALL_TALENT_LEARNED            ' ,
    'CRITERIA_TYPE_APPEARANCE_UNLOCKED_BY_SLOT          ' ,
    'CRITERIA_TYPE_ORDER_HALL_RECRUIT_TROOP             ' ,
    '// 201 - 0 criterias (Legion - 23420)',
    '// 202 - 0 criterias (Legion - 23420)',
    'CRITERIA_TYPE_COMPLETE_WORLD_QUEST                 ' ,
    '// 204 - Special criteria type to award players for' ,
    'CRITERIA_TYPE_TRANSMOG_SET_UNLOCKED                ' ,
    'CRITERIA_TYPE_GAIN_PARAGON_REPUTATION              ' ,
    'CRITERIA_TYPE_EARN_HONOR_XP                        ' ,
    '208,',
    '209,',
    '210,',
    'CRITERIA_TYPE_RELIC_TALENT_UNLOCKED                ' ,                 
];

    // enum CriteriaAdditionalCondition ModifierTree

const Modtree = [
    '//0',
    'CRITERIA_ADDITIONAL_CONDITION_SOURCE_DRUNK_VALUE       '     , // NYI
    'CRITERIA_ADDITIONAL_CONDITION_UNK2                     '     ,
    'CRITERIA_ADDITIONAL_CONDITION_ITEM_LEVEL               '     , // NYI
    'CRITERIA_ADDITIONAL_CONDITION_TARGET_CREATURE_ENTRY    '     ,
    'CRITERIA_ADDITIONAL_CONDITION_TARGET_MUST_BE_PLAYER    '     ,
    'CRITERIA_ADDITIONAL_CONDITION_TARGET_MUST_BE_DEAD      '     ,
    'CRITERIA_ADDITIONAL_CONDITION_TARGET_MUST_BE_ENEMY     '     ,
    'CRITERIA_ADDITIONAL_CONDITION_SOURCE_HAS_AURA          '     ,
    '//9',
    'CRITERIA_ADDITIONAL_CONDITION_TARGET_HAS_AURA          '     ,
    'CRITERIA_ADDITIONAL_CONDITION_TARGET_HAS_AURA_TYPE     '     ,
    '//12',
    '//13',
    'CRITERIA_ADDITIONAL_CONDITION_ITEM_QUALITY_MIN         '     ,
    'CRITERIA_ADDITIONAL_CONDITION_ITEM_QUALITY_EQUALS      '     ,
    'CRITERIA_ADDITIONAL_CONDITION_UNK16                    '     ,
    'CRITERIA_ADDITIONAL_CONDITION_SOURCE_AREA_OR_ZONE      '     ,
    'CRITERIA_ADDITIONAL_CONDITION_TARGET_AREA_OR_ZONE      '     ,
    '//19',
    'CRITERIA_ADDITIONAL_CONDITION_MAP_DIFFICULTY_OLD       '     ,
    'CRITERIA_ADDITIONAL_CONDITION_TARGET_CREATURE_YIELDS_XP'     , // NYI
    '//22',
    '//23',
    'CRITERIA_ADDITIONAL_CONDITION_ARENA_TYPE                 '   ,
    'CRITERIA_ADDITIONAL_CONDITION_SOURCE_RACE                '   ,
    'CRITERIA_ADDITIONAL_CONDITION_SOURCE_CLASS               '   ,
    'CRITERIA_ADDITIONAL_CONDITION_TARGET_RACE                '   ,
    'CRITERIA_ADDITIONAL_CONDITION_TARGET_CLASS               '   ,
    'CRITERIA_ADDITIONAL_CONDITION_MAX_GROUP_MEMBERS          '   ,
    'CRITERIA_ADDITIONAL_CONDITION_TARGET_CREATURE_TYPE       '   ,
    '//31',
    'CRITERIA_ADDITIONAL_CONDITION_SOURCE_MAP                 '   ,
    'CRITERIA_ADDITIONAL_CONDITION_ITEM_CLASS                 '   , // NYI
    'CRITERIA_ADDITIONAL_CONDITION_ITEM_SUBCLASS              '   , // NYI
    'CRITERIA_ADDITIONAL_CONDITION_COMPLETE_QUEST_NOT_IN_GROUP'   , // NYI
    '//36',
    'CRITERIA_ADDITIONAL_CONDITION_MIN_PERSONAL_RATING        '   , // NYI (when implementing don't forget about CRITERIA_CONDITION_NO_LOSE)
    'CRITERIA_ADDITIONAL_CONDITION_TITLE_BIT_INDEX            '   ,
    'CRITERIA_ADDITIONAL_CONDITION_SOURCE_LEVEL               '   ,
    'CRITERIA_ADDITIONAL_CONDITION_TARGET_LEVEL               '   ,
    'CRITERIA_ADDITIONAL_CONDITION_TARGET_ZONE                '   ,
    '//42',
    '//43',
    '//44',
    '//45',
    'CRITERIA_ADDITIONAL_CONDITION_TARGET_HEALTH_PERCENT_BELOW'   ,
    '//47',
    '//48',
    '//49',
    '//50',
    '//51',
    '//52',
    '//53',
    '//54',
    'CRITERIA_ADDITIONAL_CONDITION_UNK55                      '   ,
    'CRITERIA_ADDITIONAL_CONDITION_MIN_ACHIEVEMENT_POINTS     '   , // NYI
    '//57',
    'CRITERIA_ADDITIONAL_CONDITION_REQUIRES_LFG_GROUP         '   , // NYI
    '//59',
    'CRITERIA_ADDITIONAL_CONDITION_UNK60                      '   ,
    'CRITERIA_ADDITIONAL_CONDITION_REQUIRES_GUILD_GROUP       '   , // NYI
    'CRITERIA_ADDITIONAL_CONDITION_GUILD_REPUTATION           '   , // NYI
    'CRITERIA_ADDITIONAL_CONDITION_RATED_BATTLEGROUND         '   , // NYI
    'CRITERIA_ADDITIONAL_CONDITION_RATED_BATTLEGROUND_RATING  '   ,
    'CRITERIA_ADDITIONAL_CONDITION_PROJECT_RARITY             '   ,
    'CRITERIA_ADDITIONAL_CONDITION_PROJECT_RACE               '   ,
    'CRITERIA_ADDITIONAL_CONDITION_WORLD_STATE                '   , // NYI
    'CRITERIA_ADDITIONAL_CONDITION_MAP_DIFFICULTY             '   , // NYI
    'CRITERIA_ADDITIONAL_CONDITION_PLAYER_LEVEL               '   , // NYI
    'CRITERIA_ADDITIONAL_CONDITION_TARGET_PLAYER_LEVEL        '   , // NYI
    '//CRITERIA_ADDITIONAL_CONDITION_PLAYER_LEVEL_ON_ACCOUNT  '   , // Not verified
    '//72',
    '//CRITERIA_ADDITIONAL_CONDITION_UNK73       = 73, // Refe'   ,
    'CRITERIA_ADDITIONAL_CONDITION_SCENARIO_ID                '   , // NYI
    '//75',
    '//76',
    '//77',
    'CRITERIA_ADDITIONAL_CONDITION_BATTLE_PET_FAMILY          '   , // NYI
    'CRITERIA_ADDITIONAL_CONDITION_BATTLE_PET_HEALTH_PCT      '   , // NYI
    '//CRITERIA_ADDITIONAL_CONDITION_UNK80                    '   , // Something to do with world bosses
    'CRITERIA_ADDITIONAL_CONDITION_BATTLE_PET_ENTRY           '   , // NYI
    '//CRITERIA_ADDITIONAL_CONDITION_BATTLE_PET_ENTRY_ID      '   , // Some sort of data id?
    'CRITERIA_ADDITIONAL_CONDITION_CHALLENGE_MODE_MEDAL       '   , // NYI
    '//CRITERIA_ADDITIONAL_CONDITION_UNK84                    '   , // Quest id
    '//85',
    '//CRITERIA_ADDITIONAL_CONDITION_UNK86                    '   , // Some external event id
    '//CRITERIA_ADDITIONAL_CONDITION_UNK87                    '   , // Achievement id
    '//88',
    '//89',
    '//90',
    'CRITERIA_ADDITIONAL_CONDITION_BATTLE_PET_SPECIES         '   ,
    'CRITERIA_ADDITIONAL_CONDITION_EXPANSION                  '   ,
    ];

    Modtree[144] = 'CRITERIA_ADDITIONAL_CONDITION_GARRISON_FOLLOWER_ENTRY';
    Modtree[145] = 'CRITERIA_ADDITIONAL_CONDITION_GARRISON_FOLLOWER_QUALITY';
    Modtree[146] = 'CRITERIA_ADDITIONAL_CONDITION_GARRISON_FOLLOWER_LEVEL';
    Modtree[147] = 'CRITERIA_ADDITIONAL_CONDITION_GARRISON_RARE_MISSION';
    Modtree[149] = 'CRITERIA_ADDITIONAL_CONDITION_GARRISON_BUILDING_LEVEL';

    Modtree[167] = 'CRITERIA_ADDITIONAL_CONDITION_GARRISON_MISSION_TYPE';
    Modtree[169] = 'CRITERIA_ADDITIONAL_CONDITION_PLAYER_ITEM_LEVEL';
    Modtree[184] = 'CRITERIA_ADDITIONAL_CONDITION_GARRISON_FOLLOWER_ILVL';
    Modtree[193] = 'CRITERIA_ADDITIONAL_CONDITION_HONOR_LEVEL';
    Modtree[194] = 'CRITERIA_ADDITIONAL_CONDITION_PRESTIGE_LEVEL';


